scapegoat-scala/scapegoat

src/main/scala/com/sksamuel/scapegoat/Feedback.scala, src/main/scala/com/sksamuel/scapegoat/Inspection.scala, src/main/scala/com/sksamuel/scapegoat/plugin.scala, src/test/scala/com/sksamuel/scapegoat/FeedbackTest.scala, src/test/scala/com/sksamuel/scapegoat/PluginRunner.scala
This will let us report warnings/errors to sbt for it to handle appropriately.
This should fix sksamuel/sbt-scapegoat#25
With this change, the Feedback console output is somewhat duplicated. One thing the console output has that the sbt output doesn't is the optional snippet. That should be easy enough to send to the reporter so that the Feedback console output can go away completely.
=> Report compiler feedback to the reporter.

src/main/scala/com/sksamuel/scapegoat/inspections/collections/ArrayEquals.scala, src/test/scala/com/sksamuel/scapegoat/inspections/collections/ArrayEqualsTest.scala
Fix ArrayEquals false-positive when comparing an array to null, and include NE in the warning
=> Fix ArrayEquals false-positive when comparing an array to null

src/main/scala/com/sksamuel/scapegoat/inspections/collections/CollectionPromotionToAny.scala
The following causes the compiler to fail:
```scala
object Test extends App {
type SList = List[String]
val a: SList = List()
val b = a :+ "c"
}
```
Stacktrace
```
java.util.NoSuchElementException: head of empty list
at scala.collection.immutable.Nil$.head(List.scala:420)
at scala.collection.immutable.Nil$.head(List.scala:417)
at com.sksamuel.scapegoat.inspections.collections.CollectionPromotionToAny$$anon$2$$anon$1.isAny(CollectionPromotionToAny.scala:23)
at com.sksamuel.scapegoat.inspections.collections.CollectionPromotionToAny$$anon$2$$anon$1.isAnySeq(CollectionPromotionToAny.scala:26)
at com.sksamuel.scapegoat.inspections.collections.CollectionPromotionToAny$$anon$2$$anon$1.inspect(CollectionPromotionToAny.scala:33)
at com.sksamuel.scapegoat.InspectionContext$Traverser$class.traverse(I …
```
=> Fix java.util.NoSuchElementException: head of empty list

src/main/scala/com/sksamuel/scapegoat/inspections/equality/ComparingUnrelatedTypes.scala, src/test/scala/com/sksamuel/scapegoat/inspections/equality/ComparingUnrelatedTypesTest.scala
The existing check uses type erasure with value classes, which causes this check to pass when it shouldn't.
=> ComparingUnrelatedTypes: special case value classes

src/main/scala/com/sksamuel/scapegoat/inspections/equality/ComparingUnrelatedTypes.scala, src/test/scala/com/sksamuel/scapegoat/inspections/equality/ComparingUnrelatedTypesTest.scala
Previously this check would fail with an exception on parameterized types because
the .asClass method will throw on parameterized types.
This patch fixes that and additionally expands the checks to cover parameterized types.
=> ComparingUnrelatedTypes: expand to cover parameterized types

README.md, src/main/scala/com/sksamuel/scapegoat/ScapegoatConfig.scala, src/main/scala/com/sksamuel/scapegoat/inspections/exception/CatchException.scala, src/main/scala/com/sksamuel/scapegoat/inspections/exception/CatchFatal.scala, src/test/scala/com/sksamuel/scapegoat/inspections/exception/CatchExceptionTest.scala, src/test/scala/com/sksamuel/scapegoat/inspections/exception/CatchFatalTest.scala
Analogous to `CatchThrowable` this adds `CatchException` and `CatchFatal` inspections to flag harmful exceptions. Source: http://www.scala-lang.org/api/2.11.7/#scala.util.control.NonFatal$
=> Add CatchException and CatchFatal inspections

src/main/scala/com/sksamuel/scapegoat/ScapegoatConfig.scala, src/main/scala/com/sksamuel/scapegoat/inspections/collections/ReverseHead.scala, src/main/scala/com/sksamuel/scapegoat/inspections/collections/ReverseTailReverse.scala, src/test/scala/com/sksamuel/scapegoat/inspections/collections/ReverseHeadTest.scala, src/test/scala/com/sksamuel/scapegoat/inspections/collections/ReverseTailReverseTest.scala
Added inspections:
* reverse.tail.reverse can be replaced with init
* reverse.head can be replaced with last
=> Added checks for reverse.tail.reverse and reverse.head

src/main/scala/com/sksamuel/scapegoat/inspections/unneccesary/UnusedMethodParameter.scala, src/test/scala/com/sksamuel/scapegoat/inspections/unnecessary/UnusedMethodParameterTest.scala
Previously, we only ommitted the warning when the return type of the function is Nothing, now we also omit it when the body has type Nothing.
Rational is that return Nothing means non-normal return like throwing an exception or ???. Or also the use case of using js.native. In these cases, you shouldn't be warned when you don't use the parameters.
Also adds tests and checked that the tests succeed.
This fixes #143.
=> UnusedMethodParameter shouldn't warn for methods that have a body of type Nothing

README.md, src/main/scala/com/sksamuel/scapegoat/ScapegoatConfig.scala, src/main/scala/com/sksamuel/scapegoat/inspections/collections/CollectionIndexOnNonIndexedSeq.scala, src/test/scala/com/sksamuel/scapegoat/inspections/collections/CollectionIndexOnNonIndexedSeqTest.scala
Inspired by https://twitter.com/jshrsn/status/865677863646658560, this patch adds a new `IndexingOnANonIndexedSeq` rule which raises a warning when we see code which indexes on a `Seq` which isn't known to be an `IndexedSeq` subtype. The goal here is to make it easier to prevent cases where someone writes an `O(n^2)` loop by accident.
This rule might have prevented the following Spark bugs:
- https://github.com/apache/spark/pull/18005
- https://github.com/apache/spark/pull/8178
- https://github.com/apache/spark/pull/15221
In order to avoid false-positives from the use of `.apply(0)` instead of `.head` I chose to ignore all cases where the index is a literal.
=> Add CollectionIndexOnNonIndexedSeq rule

src/main/scala/com/sksamuel/scapegoat/Feedback.scala, src/main/scala/com/sksamuel/scapegoat/io/HtmlReportWriter.scala, src/main/scala/com/sksamuel/scapegoat/io/ScalastyleReportWriter.scala, src/main/scala/com/sksamuel/scapegoat/io/XmlReportWriter.scala
Fix for #151 
- split existing `Feedback.sourceFile` into `sourceFileFull` and `sourceFileNormalized`
- `sourceFileFull` is the absolute path of the source file on disk, now used in the Scalastyle XML generator
- `sourceFileNormalized` is used everywhere else as previously
=> Use full file path when generating Scalastyle XML report

src/main/scala/com/sksamuel/scapegoat/inspections/equality/ComparingUnrelatedTypes.scala, src/test/scala/com/sksamuel/scapegoat/inspections/equality/ComparingUnrelatedTypesTest.scala
The ComparingUnrelatedTypes rule would often trigger false positives in comparisons against integral type literals. For example,
```
val x = 1
x == 100L
```
would trigger a false positive even though this is a safe comparision because the long value `100L` fits within an `Int` type.
To avoid such false-positive, this patch extends the ComparingUnrelatedTypes rule to add special-case checks for the comparision of an integral value to a literal integral value. In such cases, we check whether the literal is a valid value of the other value's type.  Thus `(c: Char) == 97` is considered valid but `(c: Char) == 128000` is not.
Fixes #111.
=> Fix false positive in ComparingUnrelatedTypes when comparing to integral literals

src/main/scala/com/sksamuel/scapegoat/inspections/collections/ExistsSimplifableToContains.scala, src/test/scala/com/sksamuel/scapegoat/inspections/collections/ExistsSimplifableToContainsTest.scala
Use Traversable base type of container type to determine type parameter; covers parameter-less container types.
=> #164 Use Traversable base type of container type

src/main/scala/com/sksamuel/scapegoat/ScapegoatConfig.scala, src/main/scala/com/sksamuel/scapegoat/inspections/collections/MapGetAndGetOrElse.scala, src/test/scala/com/sksamuel/scapegoat/inspections/collections/MapGetAndGetOrElse.scala, src/test/scala/com/sksamuel/scapegoat/inspections/collections/MapGetAndGetOrElseTest.scala
If you need to lookup a key in a Map and then return a default value
if the key does not exist in the Map such as:
```
someMap.get(key).getOrElse(defaultValue)
```
This inspection will propose this simplified code instead:
```
someMap.getOrElse(key, defaultValue)
```
which does the same thing.
Inspired by the Intellij inspection that does the same.
=> add MapGetAndGetOrElse inspection

README.md
Adding MapGetAndGetOrElse to the list of inspections listed in the README.md.
=> update README with MapGetAndGetOrElse description

src/main/scala/com/sksamuel/scapegoat/Inspection.scala
This fixes #173 for Circe macros, at least in the case of calling
```deriveDecoder```. This could also fix other macro issues we have,
but I need someone to test this.
=> Fix issue with Circe deriveDecoder call

src/main/scala/com/sksamuel/scapegoat/inspections/matching/PartialFunctionInsteadOfMatch.scala, src/test/scala/com/sksamuel/scapegoat/inspections/matching/PartialFunctionInsteadOfMatchTest.scala
Fix for #178. Partial function style can use more than one digit after `$` in `x0$1`.
=> fix for #178

README.md
@sksamuel this should close #87 
I was going to start a maven plugin, but then just tried adding `<compilerPlugin>` to maven-scala-plugin and it works fine. So not sure we need a dedicated maven plugin for scapegoat.
=> add instructions for usage with maven

src/main/scala/com/sksamuel/scapegoat/inspections/equality/ComparingFloatingPointTypes.scala, src/main/scala/com/sksamuel/scapegoat/inspections/equality/ComparingUnrelatedTypes.scala, src/main/scala/com/sksamuel/scapegoat/inspections/equality/ComparisonWithSelf.scala, src/test/scala/com/sksamuel/scapegoat/inspections/equality/ComparingFloatingPointTypesTest.scala, src/test/scala/com/sksamuel/scapegoat/inspections/equality/ComparingUnrelatedTypesTest.scala, src/test/scala/com/sksamuel/scapegoat/inspections/equality/ComparisonWithSelfInspectionTest.scala
I investigate the cause for issue #189 and turns out it happened because the comparison inspections were only done for "==" and not for "!=". This PR aims to fix that.
=> Fix comparison inspections to also work for inequality (Issue #189)

src/main/scala/com/sksamuel/scapegoat/inspections/string/IllegalFormatString.scala, src/test/scala/com/sksamuel/scapegoat/inspections/string/IllegalFormatStringTest.scala
Without this change it improperly rejects format strings like this one:
```
"%010d".format(0)
// => "0000000000"
```
=> IllegalFormatString should allow format strings with width >= 10

src/main/scala/com/sksamuel/scapegoat/inspections/exception/UnreachableCatch.scala, src/test/scala/com/sksamuel/scapegoat/inspections/exception/UnreachableCatchTest.scala
In a try...catch that looks like this:
```
{
case e: SomeException if condition(e) =>
case e: SomeException if otherCondition(e) =>
}
```
it would incorrectly report the second case as unreachable, since it didn't
actually examine the `if ...` guards attached to each case.
This change makes it so that if a case is conditional (has a non-empty guard
attached to it), then it's not considered to be redundant with subsequent cases
against the same type, though it is still checked against
previous (unconditional) cases that might have had the same type.
Also fix the formatting of the message, which was missing a space.
=> Fix spurious UnreachableCatch when some catch cases are conditional

src/main/scala/com/sksamuel/scapegoat/inspections/string/IncorrectNumberOfArgsToFormat.scala, src/test/scala/com/sksamuel/scapegoat/inspections/string/IncorrectNumberOfArgsToFormatTest.scala
These should be matched by the scanner and then considered to not consume any
arguments to be interpolated.
=> Handle %% (literal %) in format strings

src/main/scala/com/sksamuel/scapegoat/inspections/unneccesary/UnnecessaryReturnUse.scala, src/test/scala/com/sksamuel/scapegoat/inspections/unnecessary/UnnecessaryReturnUseTest.scala
In the case that `return` is used to get out of a function early, the `UnnecessaryReturnUse` inspection throws a false positive if the return keyword happens to be at the end of a block.
=> handle false positive in unnecessary return use

README.md, src/main/scala/com/sksamuel/scapegoat/ScapegoatConfig.scala, src/main/scala/com/sksamuel/scapegoat/inspections/string/UnsafeStringContains.scala, src/test/scala/com/sksamuel/scapegoat/inspections/string/UnsafeStringContainsTest.scala
This new inspection is similar to the `UnsafeContains` exception, except that it operates on `String` instead of `List`. The purpose is to raise an error for code that is obviously wrong, like the following:
```scala
"abcdefgh".contains(new Object)
```
=> Add "unsafe string contains" inspection

src/main/scala/com/sksamuel/scapegoat/inspections/unneccesary/UnnecessaryToInt.scala, src/test/scala/com/sksamuel/scapegoat/inspections/unnecessary/UnnecessaryToIntTest.scala
The type goes trough some implicit conversions so I didn't find a good
way to actually verify that it is an java.lang.Integer. From my
observations the Integer does not have any baseClasses but scalas Int
does contains Int, AnyVal and Any.
Fixes issue #149
=> fix false positive for toInt on java Integer

src/main/scala/com/sksamuel/scapegoat/inspections/unneccesary/VarCouldBeVal.scala, src/test/scala/com/sksamuel/scapegoat/inspections/VarCouldBeValTest.scala
Previously, the VarCouldBeVal inspection attributed any errors not to the line
where the "var" was defined, but to the line where the enclosing def
started. (The snippet also showed, potentially, all of this enclosing def.)
Instead, we now remember the tree (of type ValDef) that defines each var, and
if it turns out that it's unwritten, we output the line number and snippet
corresponding to that tree.
=> Fix line numbers and snippets for VarCouldBeVal

src/main/scala/com/sksamuel/scapegoat/Feedback.scala, src/main/scala/com/sksamuel/scapegoat/plugin.scala, src/test/scala/com/sksamuel/scapegoat/FeedbackTest.scala
fixes #215 
It adds `sourcePath` property for the cases when sources are not in `src/main/scala` folder
Also, the `-Pscapegoat:sourcePrefix:<smth>` compiler option is added.
If the solution makes sense, I'll add a PR to the https://github.com/sksamuel/sbt-scapegoat to integrate the new property.
=> Add sourcePath property

src/main/scala/com/sksamuel/scapegoat/io/HtmlReportWriter.scala
Loading the generated HTML report over https:// results in blocked mixed content errors due to the default security policy:
```
Blocked loading mixed active content “http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css”
Blocked loading mixed active content “http://fonts.googleapis.com/css?family=Ubuntu:300,400,500,700,300italic,400italic,500italic,700italic”
Blocked loading mixed active content “http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800”
```
=> Use https protocol for stylesheet links

src/main/scala/com/sksamuel/scapegoat/inspections/collections/ComparisonToEmptySet.scala, src/test/scala/com/sksamuel/scapegoat/inspections/collections/ComparisonToEmptySetTest.scala
We are receiving a warning for the following code:
```scala
if (aSet == Set("abc")) ...
```
This PR fixes the inspection to only consider `Set()` as empty, not `Set(x[, y...])`.
=> Fix false positive comparison to empty Set

.travis.yml, build.sbt, src/main/scala/com/sksamuel/scapegoat/Feedback.scala, src/main/scala/com/sksamuel/scapegoat/inspections/NoSuperClone.scala, src/main/scala/com/sksamuel/scapegoat/inspections/collections/CollectionPromotionToAny.scala, src/main/scala/com/sksamuel/scapegoat/inspections/collections/MapGetAndGetOrElse.scala, src/main/scala/com/sksamuel/scapegoat/inspections/collections/PredefSeqIsMutable.scala, src/main/scala/com/sksamuel/scapegoat/inspections/equality/ComparisonWithSelf.scala, src/main/scala/com/sksamuel/scapegoat/inspections/inference/ProductWithSerializableInferred.scala, src/main/scala/com/sksamuel/scapegoat/inspections/math/UseExpM1.scala, src/main/scala/com/sksamuel/scapegoat/inspections/math/UseSqrt.scala, src/main/scala/com/sksamuel/scapegoat/inspections/math/ZeroNumerator.scala, src/main/scala/com/sksamuel/scapegoat/inspections/nulls/NullAssignment.scala, src/main/scala/com/sksamuel/scapegoat/inspections/string/UnsafeStringContains.scala, src/main/scala/com/sksamuel/scapegoat/io/ScalastyleReportWriter.scala, src/main/scala/com/sksamuel/scapegoat/package.scala, src/test/scala/com/sksamuel/scapegoat/FeedbackTest.scala, src/test/scala/com/sksamuel/scapegoat/inspections/WhileTrueTest.scala, src/test/scala/com/sksamuel/scapegoat/inspections/collections/JavaConversionsUseTest.scala, src/test/scala/com/sksamuel/scapegoat/inspections/collections/PredefSeqIsMutableTest.scala, src/test/scala/com/sksamuel/scapegoat/inspections/collections/PredefTraversableIsMutableTest.scala, src/test/scala/com/sksamuel/scapegoat/inspections/matching/PartialFunctionInsteadOfMatchTest.scala, src/test/scala/com/sksamuel/scapegoat/inspections/string/EmptyInterpolatedStringTest.scala, src/test/scala/com/sksamuel/scapegoat/inspections/unnecessary/NoOpOverrideTest.scala
Scala 2.13 is finally available. :tada: 
Since we are using scapegoat in our projects, we need a release for 2.13.
This PR is migrating the inspections to 2.13 while keeping compatibility with 2.11 and 2.12.
*breaking changes*:
* String interpolations are no longer recognized, since they are macro expanded (see [FastStringInterpolator.scala:23](https://github.com/scala/scala/blob/f1dec97ed35ba60ef1489592f230a00ed7184545/src/compiler/scala/tools/reflect/FastStringInterpolator.scala#L23))
* `JavaConversions` are gone in 2.13, test code compilation fails with `object JavaConversions is not a member of package collection`
* `scala.Seq` is now aliased to `scala.collections.immutable.Seq` instead of `scala.collections.Seq` - makes the (ineptly named) `PredefSeqIsMutable` inspection obsolete
* …
=> Scala 2.13 support

src/main/scala/com/sksamuel/scapegoat/Inspection.scala, src/main/scala/com/sksamuel/scapegoat/inspections/collections/ArrayEquals.scala, src/main/scala/com/sksamuel/scapegoat/inspections/collections/AvoidSizeEqualsZero.scala, src/main/scala/com/sksamuel/scapegoat/inspections/collections/CollectionIndexOnNonIndexedSeq.scala, src/main/scala/com/sksamuel/scapegoat/inspections/collections/CollectionNamingConfusion.scala, src/main/scala/com/sksamuel/scapegoat/inspections/collections/CollectionNegativeIndex.scala, src/main/scala/com/sksamuel/scapegoat/inspections/collections/ExistsSimplifiableToContains.scala, src/main/scala/com/sksamuel/scapegoat/inspections/collections/ListAppend.scala, src/main/scala/com/sksamuel/scapegoat/inspections/collections/ListSize.scala, src/main/scala/com/sksamuel/scapegoat/inspections/collections/MapGetAndGetOrElse.scala, src/main/scala/com/sksamuel/scapegoat/inspections/collections/NegationIsEmpty.scala, src/main/scala/com/sksamuel/scapegoat/inspections/collections/NegationNonEmpty.scala, src/main/scala/com/sksamuel/scapegoat/inspections/collections/ReverseTailReverse.scala, src/main/scala/com/sksamuel/scapegoat/inspections/collections/ReverseTakeReverse.scala, src/main/scala/com/sksamuel/scapegoat/inspections/collections/SwapSortFilter.scala, src/main/scala/com/sksamuel/scapegoat/inspections/collections/TraversableHead.scala, src/main/scala/com/sksamuel/scapegoat/inspections/collections/TraversableLast.scala, src/main/scala/com/sksamuel/scapegoat/inspections/collections/UnsafeContains.scala, src/main/scala/com/sksamuel/scapegoat/inspections/string/ArraysInFormat.scala, src/main/scala/com/sksamuel/scapegoat/inspections/string/ArraysToString.scala
This PR removes all uses of existential types and Scapegoat types in `typeOf[]`. If Scapegoat classes are not on the compile classpath then these `typeOf`s caused `scala.ScalaReflectionException: object <type> in compiler mirror not found` exceptions during compilation (see #222, #167, #163, #98).
To do this, I added several `is<type>(tree: Tree)` helper methods to the `InspectionContext.Traverser` trait. There's a couple of details which I'll discuss in PR self-review comments.
I tested this by integrating Scapegoat into a Bazel build.
Fixes #222.
=> Remove use of existential types and Scapegoat types in typeOf

README.md, src/test/scala/com/sksamuel/scapegoat/ReadmeTest.scala
This PR adds more details about command line flags in the readme.
It might be useful if we build GH-pages for the project.
=> Better compiler flag description

build.sbt, project/plugins.sbt
Starting with Scala 2.13, the scala-xml is no longer included in the
distribution and no longer automatically available on the compiler's classpath.
Furthermore, in Scala < 2.13, the compiler did provide the module on the
classpath, but you could not choose which version.
As it seems, there is currently no way to add dependencies to the compiler's classpath.
Fixes sksamuel/sbt-scapegoat#91.
[previously](https://stackoverflow.com/questions/24972955/sbt-plugin-add-dependency-to-project-build-sbt)
=> Embed shaded scala-xml and scala-collection-compat modules

README.md, src/main/scala/com/sksamuel/scapegoat/Feedback.scala, src/main/scala/com/sksamuel/scapegoat/io/HtmlReportWriter.scala, src/main/scala/com/sksamuel/scapegoat/io/ScalastyleReportWriter.scala, src/main/scala/com/sksamuel/scapegoat/io/XmlReportWriter.scala, src/main/scala/com/sksamuel/scapegoat/plugin.scala, src/test/scala/com/sksamuel/scapegoat/FeedbackTest.scala, src/test/scala/com/sksamuel/scapegoat/PluginRunner.scala
refs #181
It adds `minimalLevel` property, that defaults to `Levels.Info`.
Also, the -Pscapegoat:minimalLevel:<level> compiler option is added.
If specified, the output will be filtered by level, for ex. if it is set to `warning`, only warnings and errors will be displayed in the reports. Triggered inspections count is not affected by this change, all numbers will be visible in HTML report.
=> Output filtering by level of inspection

src/main/scala/com/sksamuel/scapegoat/Inspection.scala, src/test/scala/com/sksamuel/scapegoat/inspections/collections/TraversableHeadTest.scala
This PR makes the `SuppressWarnings` annotation work more broadly. It should now be possible to annotate any member of a structure (including `val` members, which were the initial problem I was trying to solve). I added some tests for the new functionality to the `TraversableHeadTest` because I didn't see a test class specific to the warning suppression.
I also refactored the `isThisDisabled` method a bit (and merged the `isAllDisabled` functionality into it) to destructure the annotation arguments rather than relying on string processing, which should prevent false positives due to an unexpected substring match. I made it so users can also specify the full canonical class name when listing classes to suppress.
=> Improve SuppressWarnings support to work for all members

src/main/scala/com/sksamuel/scapegoat/inspections/math/UseSqrt.scala, src/main/scala/com/sksamuel/scapegoat/inspections/option/OptionSize.scala
Minor contribution. Fixing compiler warnings:
- syntax for `=>` in 2.13
- and useless expression
=> [minor] Fixing syntax warnings

README.md, src/main/scala/com/sksamuel/scapegoat/plugin.scala
Currently you can disable (black list) some inspections. What would be useful if you could start from empty set of inspections and gradually add (white list) some of them.
Thus adding support for `-P:scapegoat:enabledInspections` argument with same syntax.
I find it a blocker for adoption at a large code base where I don't stand a chance to fix all the bugs / code smells in one go.
Also fixing an inconsistency, the help text incorrectly mentioned `disabled` as existing argument name while it's `disabledInspections`.
- sadly no UT coverage
- I've tested by executing in a Maven profile, with and without the new argument. Subsequently I saw tons and a few failures reported. As expected.
=> Providing support for enabledInspections

src/main/scala/com/sksamuel/scapegoat/inspections/collections/ExistsSimplifiableToContains.scala, src/test/scala/com/sksamuel/scapegoat/inspections/collections/ExistsSimplifiableToContainsTest.scala
It turns out the method `.contains()` is not defined in Traversable interface. Only (some) subinterfaces do offer this. Thus Scapegoat is not right suggesting to replace `exists()` with `contains()` in some cases.
An example of such situation is `Iterable[T]` which doesn't define `.contains()`.
=> False positive: Traversable.exists(...) is not always simplifiable to .contains()

src/main/scala/com/sksamuel/scapegoat/inspections/NoOpOverride.scala, src/test/scala/com/sksamuel/scapegoat/inspections/unnecessary/NoOpOverrideTest.scala
Fixing another false positive - when a method is an override, its only body is to call super, but with different args. The Scapegoat suggestion of the override being unnecessary doesn't make sense.
=> False positive: super different args

src/main/scala/com/sksamuel/scapegoat/inspections/collections/PreferSetEmpty.scala, src/test/scala/com/sksamuel/scapegoat/inspections/collections/PreferSetEmptyTest.scala
The hint to use `Set.empty` instead of `Set()` is relevant only if immutable sets are used. For mutable sets the suggestion is invalid.
=> False positive: suggests Set.empty() for mutable Sets

src/main/scala/com/sksamuel/scapegoat/inspections/unneccesary/VarCouldBeVal.scala, src/test/scala/com/sksamuel/scapegoat/inspections/VarCouldBeValTest.scala
Fixing `VarCouldBeVal` false positives for code which modifies the var reference in `while(...) {}` condition (not the body). I guess it fixes the `if (...) {}` situations too.
=> False positive: while varcouldbeval

.travis.yml, README.md, build.sbt, project/build.properties, project/plugins.sbt, src/main/scala/com/sksamuel/scapegoat/plugin.scala, src/test/scala/com/sksamuel/scapegoat/PluginRunner.scala, version.sbt
As a rule of thumb, a scalac plugin always should be published using the full
scala version in its name, since scalac's internal APIs can change without notice.
This change introduces the sbt-travisci plugin which makes it easier to
maintain a full set of versions, cross compiled and run through the CI.
Fixes #248.
=> Publish with full Scala version

src/main/scala/com/sksamuel/scapegoat/Feedback.scala, src/main/scala/com/sksamuel/scapegoat/plugin.scala
Fixes #247 by providing a possibility to set an override for `all` inspection, e.g.
>  -P:scapegoat:overrideLevels:all=Error
Tested by running a Maven build with this setting and observing all the reported failures to be Errors in `xml` and `stdout` output.
=> Support for `all` in overrideLevels

src/main/scala/com/sksamuel/scapegoat/inspections/string/IncorrectNumberOfArgsToFormat.scala, src/test/scala/com/sksamuel/scapegoat/inspections/string/IncorrectNumberOfArgsToFormatTest.scala
`%n` is a valid String format specifier which doesn't take arguments, it stands for line separator as per [Javadoc](https://docs.oracle.com/javase/9/docs/api/java/util/Formatter.html#syntax):
>>> 'n'
>>> The conversion does not correspond to any argument. 
>>> the platform-specific line separator as returned by System.lineSeparator().
=> False positive: `%n` String format

src/main/scala/com/sksamuel/scapegoat/inspections/collections/PreferMapEmpty.scala, src/main/scala/com/sksamuel/scapegoat/inspections/collections/PreferSeqEmpty.scala, src/main/scala/com/sksamuel/scapegoat/inspections/collections/PreferSetEmpty.scala, src/test/scala/com/sksamuel/scapegoat/inspections/collections/PreferMapEmptyTest.scala, src/test/scala/com/sksamuel/scapegoat/inspections/collections/PreferSeqEmptyTest.scala
- Continuation of #253 - applying the same thought for Maps and Seqs - i.e. not suggesting `.empty()` for mutable collections
- Also changing the actual warning message to be more precise. I mean in the following example:
```
val a = Set()
```
it's not the `a` Set which is the object created. It's not. Actually there's a singleton returned there which could be easily checked with:
```
(1 to 10).map(_ => java.lang.System.identityHashCode(Set()))
res38: scala.collection.immutable.IndexedSeq[Int] = Vector(2070333417, 2070333417, 2070333417, 2070333417, 2070333417, 2070333417, 2070333417, 2070333417, 2070333417, 2070333417)
```
But the inspection is right. During `Set()` call there's an intermediate builder object created, which is not preferable.
=> False positives: not suggesting .empty() for mutable collections

src/main/scala/com/sksamuel/scapegoat/inspections/equality/ComparingUnrelatedTypes.scala, src/test/scala/com/sksamuel/scapegoat/inspections/equality/ComparingUnrelatedTypesTest.scala
* use `widen` to extract a base type from a singleton type (`x.type`)
* check whether LHS operand has a specialized `==` or `!=` method for the RHS type
Fixes #235 and fixes #260. Supersedes #236.
=> Fix false positives for ComparingUnrelatedTypes inspection

src/main/scala/com/sksamuel/scapegoat/inspections/exception/SwallowedException.scala, src/test/scala/com/sksamuel/scapegoat/inspections/exception/SwallowedExceptionTest.scala
Amending the `SwallowedException` inspection to check also against masked exceptions (maybe the inspection should be renamed then?), e.g.
```
object Test {
try {
println(Integer.valueOf("asdf"))
} catch {
case nfe: NumberFormatException =>
throw new IllegalArgumentException("not a number")
}
}
```
hides the real cause of the exception thrown. Thus caused-by section doesn't appear in the eventual stack trace
=> New (sub-)inspection: Masking exceptions

.github/release-drafter.yml, .github/workflows/release-drafter.yml, .gitignore
This PR adds [release drafter](https://github.com/marketplace/actions/release-drafter) config and a GitHub action to update the current release draft every time a PR gets merged to master.
I've set up the categories based on existing labels, but I also added
- `Maintenance` (I'd recommend adding a new label `chore` for any maintenance related work), and
- `Dependency updates` - for when scapegoat gets added to Scala Steward.
Closes #273.
=> Add release drafter.

.mergify.yml
I've added mergify config to automatically label PRs from Scala Steward as `dependency-update`, which aligns with the label I added to release drafter config [here](https://github.com/sksamuel/scapegoat/blob/master/.github/release-drafter.yml#L19).
In order for this to work a maintainer needs to add the `dependency-update` label and enable mergify for this project https://dashboard.mergify.io. We should do the same for sbt-scapegoat.
=> Add mergify to label dependency updates from Scala Steward.

build.sbt
Disabling coursier as it causes `2.13.0` tests to fail
=> Fixes #298. Disabling coursier

src/main/scala/com/sksamuel/scapegoat/inspections/collections/ExistsSimplifiableToContains.scala, src/test/scala/com/sksamuel/scapegoat/inspections/collections/ExistsSimplifiableToContainsTest.scala
Fixing #297 by making the criteria for `ExistsSimplifiableToContains` more precise.
e.g. `exists(string => string.toLowerCase == string)` is not replacable with `contains`
=> Making ExistsSimplifiableToContains more precise

.travis.yml
With coursier disabled in #299, running tests against 2.13.0 should be working again.
=> Add 2.13.0 back to the build matrix.

src/main/scala/com/sksamuel/scapegoat/inspections/collections/CollectionPromotionToAny.scala, src/test/scala/com/sksamuel/scapegoat/inspections/collections/CollectionPromotionToAnyTest.scala
Fixing #315 which turns out to be a special case of `Seq.empty[Any]` which is not handled way. It turns out Seq.empty's full type does not start with `scala.collection.immutable` (at least in 2.12)
=> Fixing (Collection[Any] warnings of promotion to Collection[Any]) for Seq.empty

src/main/scala/com/sksamuel/scapegoat/inspections/empty/EmptyMethod.scala, src/test/scala/com/sksamuel/scapegoat/inspections/empty/EmptyMethodTest.scala
To define empty methods is a valid technique especially in interfaces (internal interfaces within the program, or APIs). I agree an empty private method should be avoided.
=> False-positive - empty methods no so empty

src/main/scala/com/sksamuel/scapegoat/inspections/math/UseLog1P.scala, src/main/scala/com/sksamuel/scapegoat/inspections/option/OptionGet.scala, src/main/scala/com/sksamuel/scapegoat/inspections/unsafe/AsInstanceOf.scala
It appears that I've missed one.
=> Add a description to the AsInstanceOf inspection.

src/main/scala/com/sksamuel/scapegoat/inspections/LonelySealedTrait.scala, src/main/scala/com/sksamuel/scapegoat/inspections/collections/ComparisonToEmptyList.scala, src/main/scala/com/sksamuel/scapegoat/inspections/collections/ComparisonToEmptySet.scala, src/main/scala/com/sksamuel/scapegoat/inspections/collections/ExistsSimplifiableToContains.scala, src/main/scala/com/sksamuel/scapegoat/inspections/collections/FilterDotHead.scala, src/main/scala/com/sksamuel/scapegoat/inspections/collections/FilterDotHeadOption.scala, src/main/scala/com/sksamuel/scapegoat/inspections/collections/FilterDotIsEmpty.scala, src/main/scala/com/sksamuel/scapegoat/inspections/collections/FilterDotSize.scala, src/main/scala/com/sksamuel/scapegoat/inspections/collections/FilterOptionAndGet.scala, src/main/scala/com/sksamuel/scapegoat/inspections/collections/FindAndNotEqualsNoneReplaceWithExists.scala, src/main/scala/com/sksamuel/scapegoat/inspections/collections/FindDotIsDefined.scala, src/main/scala/com/sksamuel/scapegoat/inspections/collections/ReverseFunc.scala, src/main/scala/com/sksamuel/scapegoat/inspections/collections/ReverseTailReverse.scala, src/main/scala/com/sksamuel/scapegoat/inspections/collections/ReverseTakeReverse.scala, src/main/scala/com/sksamuel/scapegoat/inspections/collections/UnsafeContains.scala, src/main/scala/com/sksamuel/scapegoat/inspections/controlflow/RepeatedIfElseBody.scala, src/main/scala/com/sksamuel/scapegoat/inspections/math/BigDecimalScaleWithoutRoundingMode.scala, src/main/scala/com/sksamuel/scapegoat/inspections/math/BrokenOddness.scala, src/main/scala/com/sksamuel/scapegoat/inspections/unsafe/FinalizerWithoutSuper.scala, src/main/scala/com/sksamuel/scapegoat/io/HtmlReportWriter.scala, src/main/scala/com/sksamuel/scapegoat/plugin.scala, src/test/scala/com/sksamuel/scapegoat/AllInspectionsTest.scala
Following #330 adding a unit-test for enforcing some basic formatting expectations towards `description` and `explanation` of inspections.
Also the code samples within `description` and `explanation` should be made within backticks.
=> Enforcing proper formatting of descriptions and explanations

src/main/scala/com/sksamuel/scapegoat/Feedback.scala, src/main/scala/com/sksamuel/scapegoat/plugin.scala, src/test/scala/com/sksamuel/scapegoat/FeedbackTest.scala, src/test/scala/com/sksamuel/scapegoat/inspections/collections/MapGetAndGetOrElseTest.scala
Currently, any warning is reported twice (depending on the minimal level and the current level of the warning): once using println, and once properly using the given reporter.
Using `println` is bad for several reasons; the output looks different (ie. the level is not colored, it prints "warnings" instead of "warn"), it cannot be filtered via SBT's LogManager facility (ie. by switching the log level).
This PR simply uses the given reporter to report findings in standard format to the console. It also uses a normal filename instead of the weird "normalized" file name (I really would like to get rid of the `normalizedSourceFile` -- I cannot think of a reason someone would want this...)
Also, output is marked with `[scapegoat]` to inform users that Scapegoat is the origin of the reported …
=> Only report warnings via the reporter

.github/workflows/master-release.yml, build.sbt, project/plugins.sbt, version.sbt
This PR adds a release workflow using sbt-ci-release.
Here is how it works:
1. This workflow gets run every time a PR is merged to master and publishes a snapshot release for each version defined in the build.sbt file (we agreed we would release for the latest version of 2.11 and the two recent releases of 2.12 and 2.13). The snapshot is in the following format, e.g. `1.4.2+11-01b5562a+20200328-1650-SNAPSHOT` - it comprises of the most recent tag + distance of the HEAD commit from the tag (11 in this case), SHA of the HEAD (01b5562a), the current timestamp and the suffix `-SNAPSHOT`.
2. This workflow also runs each time a new tag is pushed to the repo and publishes a new release using the tag as the new version. sbt-ci-release identifies automatically that it needs to release a regular …
=> Add a release workflow.

.github/workflows/pr-checks.yml, build.sbt, project/plugins.sbt
Currently blocked by the semanticdb for 2.13.2. I can see a new scalameta has just been released, so hopefully, it shouldn't be too long until it makes its way to the sbt-scalafix plugin.
Closes #350.
=> Cross-build for 2.13.2.

src/main/scala/com/sksamuel/scapegoat/inspections/collections/AvoidSizeNotEqualsZero.scala, src/test/scala/com/sksamuel/scapegoat/inspections/collections/AvoidSizeNotEqualsZeroTest.scala
=> `.size > 0` checks in collections

src/main/scala/com/sksamuel/scapegoat/inspections/collections/CollectionPromotionToAny.scala, src/main/scala/com/sksamuel/scapegoat/inspections/collections/PreferMapEmpty.scala, src/main/scala/com/sksamuel/scapegoat/inspections/collections/PreferSeqEmpty.scala, src/main/scala/com/sksamuel/scapegoat/inspections/collections/PreferSetEmpty.scala, src/main/scala/com/sksamuel/scapegoat/inspections/inference/PointlessTypeBounds.scala
Any text block wrapped in `[]` gets parsed as a link with an empty URL, so I wrapped those instances in an inline code block along with some other code blocks I identified in the same files.
We should also probably strip the `` ` `` character from the console output (and HTML reports too) - I'm happy to do that in a separate PR if I get any 👍  here.
=> Fix markdown formatting.

.github/workflows/pr-checks.yml, .scalafmt.conf, build.sbt, src/main/scala/com/sksamuel/scapegoat/inspections/option/EitherGet.scala, src/test/scala/com/sksamuel/scapegoat/FeedbackTest.scala, src/test/scala/com/sksamuel/scapegoat/PluginRunner.scala, src/test/scala/com/sksamuel/scapegoat/inspections/FinalModifierOnCaseClassTest.scala
Scala 2.13.3 has been released, the semanticdb scalac plugin for it is already available.
=> Scala 2.13.3

src/test/scala/com/sksamuel/scapegoat/inspections/VariableShadowingTest.scala
Unit Test for one of the cases reported in #398: https://github.com/sksamuel/scapegoat/issues/398#issuecomment-652679499
=> UT for Variable Shadowing false positive

src/main/scala/com/sksamuel/scapegoat/Feedback.scala, src/main/scala/com/sksamuel/scapegoat/Inspection.scala, src/main/scala/com/sksamuel/scapegoat/plugin.scala, src/test/scala/com/sksamuel/scapegoat/FeedbackTest.scala
This done so they can be suppressed more easily if needed.
Solves #264
=> Log the name of the Inspection

src/main/scala/com/sksamuel/scapegoat/inspections/collections/ComparisonToEmptyList.scala, src/test/scala/com/sksamuel/scapegoat/inspections/collections/ComparisonToEmptyListTest.scala
In my previous commit 9ccd7405 there was no check verifying that 'apply' method is called on 'List' type, and because of that false positives were reported in cases like this:
```
object Test {
case class Paramless[T]()
val a = List(1,2,3)
val b = a == Paramless()
}
```
=> Fix false positive in ComparisonToEmptyList inspection

src/main/scala/com/sksamuel/scapegoat/Configuration.scala, src/main/scala/com/sksamuel/scapegoat/Feedback.scala, src/main/scala/com/sksamuel/scapegoat/Inspections.scala, src/main/scala/com/sksamuel/scapegoat/plugin.scala, src/test/scala/com/sksamuel/scapegoat/AllInspectionsTest.scala, src/test/scala/com/sksamuel/scapegoat/ConfigurationTest.scala, src/test/scala/com/sksamuel/scapegoat/FeedbackTest.scala, src/test/scala/com/sksamuel/scapegoat/PluginRunner.scala, src/test/scala/com/sksamuel/scapegoat/ReadmeTest.scala, src/test/scala/com/sksamuel/scapegoat/TestConfiguration.scala
#439 suggests we should offer another way of configuring Scapegoat.
Before that happens, let's clean-up the process of parsing/accepting the configuration input.
Pure refactoring, no changes to the logic (... intended).
=> Refactoring configuration parsing

.github/workflows/master-release.yml
**Why**
I have a fork of this repo which I keep on updating. Every time I do that I get an email from Github:
>  [mccartney/scapegoat] Release workflow run 
> Release: All jobs have failed
The run fails with this error message:
> gpg: no valid OpenPGP data found.
No surprise my fork shouldn't be able to publish a snapshot release of the library.
**What**
Attempt at having the action run only in the main repo.
=> Run the release Github Action only in the main repo, not in forks

.github/workflows/master-release.yml
After #546, the Github Actions need to be updated.
=> Update Github Actions to reflect new org name

build.sbt, project/plugins.sbt
Updates to Scala 2.13.7 and adds two new compiler flags introduced in the latest versions to make use of strict pattern matching and ease the migration to Scala 3.
It would be nice if you release a new version soon.
Fixes #581.
Closes #582. Closes #583. Closes #584.
=> #581: Update to Scala 2.13.7

src/main/scala/com/sksamuel/scapegoat/inspections/VariableShadowing.scala, src/main/scala/com/sksamuel/scapegoat/inspections/collections/DuplicateMapKey.scala, src/main/scala/com/sksamuel/scapegoat/inspections/collections/UnsafeTraversableMethods.scala, src/test/scala/com/sksamuel/scapegoat/inspections/collections/UnsafeTraversableMethodsTest.scala
Unsafe methods on traversables were not caught if they were followed by another method call because of the missing `else continue(tree)` part.
I've called the test case `Regression` even though this never worked correctly so I'm up for changing that if there's a suggestion for a better name.
=> Find unsafe traversable methods in method chains

.scalafmt.conf
Reverts scapegoat-scala/scapegoat#608
because of [the failure registered by CI](https://github.com/scapegoat-scala/scapegoat/runs/4749829472?check_suite_focus=true), which boiled down to:
```
exec /home/runner/bin/jabba install adopt@1.8.0-292
Installing adopt@1.8.0-292
Downloading adopt@1.8.0-292 (https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u292-b10/OpenJDK8U-jdk_x64_linux_hotspot_8u292b10.tar.gz) 
Extracting /tmp/jabba-d-851022420 to /home/runner/.jabba/jdk/adopt@1.8.0-292 
gzip: invalid header 
0/489
Error: exec: Downloading adopt@1.8.0-292 (https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u292-b10/OpenJDK8U-jdk_x64_linux_hotspot_8u292b10.tar.gz) 
Extracting /tmp/jabba-d-851022420 to /home/runner/.jabba/jdk/adopt@1.8.0-292 
gzip: …
```
=> Revert "Update scalafmt-core to 3.3.1"

src/main/scala/com/sksamuel/scapegoat/io/ScalastyleReportWriter.scala
Hi! 👋 
I'm currently adding this GitHub Action to our pipeline to display and annotate the code with the results from the scapegoat-run. Unfortunately, everything is just an "Annotation", because the GH Action expects the `severity` in the xml to be lowercase.
The DTD unfortunately doesn't define the `severity` attribute (https://checkstyle.org/dtds/configuration_1_3.dtd), but 
* the `google_checks` use `warning` as default: https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/google_checks.xml#L22
* the puppycrawl-implementation explicitly changes to lowercase: https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/SeverityLevel.java#L56
* the `sun_checks` use `error` as default: …
=> Change severity in Checkstyle output to lowercase

.scalafmt.conf, src/main/scala/com/sksamuel/scapegoat/Configuration.scala, src/main/scala/com/sksamuel/scapegoat/Inspection.scala, src/main/scala/com/sksamuel/scapegoat/inspections/AvoidToMinusOne.scala, src/main/scala/com/sksamuel/scapegoat/inspections/RedundantFinalModifierOnMethod.scala, src/main/scala/com/sksamuel/scapegoat/inspections/RedundantFinalModifierOnVar.scala, src/main/scala/com/sksamuel/scapegoat/inspections/collections/CollectionNamingConfusion.scala, src/main/scala/com/sksamuel/scapegoat/inspections/collections/FilterDotHeadOption.scala, src/main/scala/com/sksamuel/scapegoat/inspections/collections/FilterDotIsEmpty.scala, src/main/scala/com/sksamuel/scapegoat/inspections/collections/ReverseFunc.scala, src/main/scala/com/sksamuel/scapegoat/inspections/collections/UnsafeContains.scala, src/main/scala/com/sksamuel/scapegoat/inspections/math/BigDecimalScaleWithoutRoundingMode.scala, src/main/scala/com/sksamuel/scapegoat/inspections/math/UseCbrt.scala, src/main/scala/com/sksamuel/scapegoat/inspections/math/UseLog10.scala, src/main/scala/com/sksamuel/scapegoat/inspections/math/UseLog1P.scala, src/main/scala/com/sksamuel/scapegoat/io/ScalastyleReportWriter.scala
`unindentTopLevelOperators` was removed in https://github.com/scalameta/scalafmt/commit/9402b81a4de3ba876303ca3cdff0fcac1f88d2c2.
`indentOperator.topLevelOnly` should be used instead.
Updated the config with that change and reformatted all files.
=> Fix Scalafmt config & format

build.sbt, src/main/scala/com/sksamuel/scapegoat/inspections/BooleanParameter.scala, src/test/scala/com/sksamuel/scapegoat/inspections/BooleanParameterTest.scala
I made an error in my last PR because I didn't know that for any `case class` with a Boolean parameter the compiler actually creates a method called `<init>` in the automatically generated companion object that has the constructor parameters. In that method's parameters there's obviously also the Boolean parameter. We don't want to show an info for `case class`es, though.
This filters for these methods and adds a negative test as well.
Could we get this merged and released quickly?
=> Fix: Inform about Boolean Parameters not for case class initializer

README.md, src/main/scala/com/sksamuel/scapegoat/Inspections.scala, src/main/scala/com/sksamuel/scapegoat/inspections/exception/CatchExceptionImmediatelyRethrown.scala, src/test/scala/com/sksamuel/scapegoat/inspections/exception/CatchExceptionImmediatelyRethrownTest.scala
* Inspections now available when throwables/exceptions are immediately
rethrown in a catch block implementation.
=> Adding inspection for immediate rethrows

.github/workflows/pr-checks.yml, README.md, build.sbt, src/test/scala/com/sksamuel/scapegoat/inspections/equality/ComparingUnrelatedTypesTest.scala, src/test/scala/com/sksamuel/scapegoat/inspections/matching/PartialFunctionInsteadOfMatchTest.scala
It was released last month. I wanted to update a cross-built library but Scapegoat failed. This adds the relevant support.
=> Support Scala 2.12.16

build.sbt
When running projects from IDE, intellij (somewhat) incorrectly puts scapegoat on the classpath as well, causing issues with some of the scala-collection-compat classes due to binary mismatches.
The scala-collection-compat jar has a few classes outside of `scala.collection.compat.**` (like scala.jdk.CollectionConverters$). With this fix all of the classes are shaded into scapegoat.x packages removing the potential clash with the regular scala-collection-compat
Note: The version currently used in scapegoat only has some util.compat classes (seem the old versions had more), I've narrowed the scope down to only shade that path
=> Shade all of scala-collection-compat

src/main/scala/com/sksamuel/scapegoat/inspections/collections/PredefIterableIsMutable.scala, src/main/scala/com/sksamuel/scapegoat/inspections/collections/PredefTraversableIsMutable.scala, src/test/scala/com/sksamuel/scapegoat/inspections/collections/PredefIterableIsMutableTest.scala
=> PredefTraversableIsMutable & PredefIterableIsMutable don't apply on Scala 2.13

build.sbt, src/main/scala/com/sksamuel/scapegoat/inspections/collections/PredefIterableIsMutable.scala, src/main/scala/com/sksamuel/scapegoat/inspections/collections/PredefTraversableIsMutable.scala, src/test/scala/com/sksamuel/scapegoat/FeedbackTest.scala, src/test/scala/com/sksamuel/scapegoat/inspections/BooleanParameterTest.scala, src/test/scala/com/sksamuel/scapegoat/inspections/collections/PredefIterableIsMutableTest.scala
These deprecations came into effect with Scala 2.12. Since we dropped support for Scala 2.11, I did the changes.
Also removing some specific scalac options for not any longer supported patch versions of Scala 2.13.
=> Address deprecations in FeedbackTest

src/main/scala/com/sksamuel/scapegoat/inspections/equality/ComparingUnrelatedTypes.scala, src/test/scala/com/sksamuel/scapegoat/inspections/equality/ComparingUnrelatedTypesTest.scala
```
scala> BigDecimal(5) == 0
val res0: Boolean = false
scala> BigDecimal(0) == 0
val res1: Boolean = true
```
Scapegoat still seem to get the Literal instead of the boxed variants which I observed in bytecode after diagnosing a violation in my codebases. This special clause will handle these cases.
=> Reduce false positives on comparing unrelated types

src/test/scala/com/sksamuel/scapegoat/inspections/collections/ExistsSimplifiableToContainsTest.scala
Fixes #122. Added the test just to confirm we don't have a false positive. I think it's worth keeping for the future.
=> Add test for ExistsSimplifiableToContains

src/main/scala/com/sksamuel/scapegoat/inspections/empty/EmptyIfBlock.scala, src/test/scala/com/sksamuel/scapegoat/inspections/empty/EmptyIfBlockTest.scala
Fixes #229 
While I don't fully agree with the presented sample, I do agree with the spirit. So a more generic solution is to ignore the If blocks entirely if they're the body of a Function (ie, they affect the return types).
=> Allow empty if statements if they're captured by a function

src/main/scala/com/sksamuel/scapegoat/io/HtmlReportWriter.scala
=> Decorate code in html report

README.md, src/main/scala/com/sksamuel/scapegoat/Configuration.scala, src/main/scala/com/sksamuel/scapegoat/Feedback.scala, src/main/scala/com/sksamuel/scapegoat/Level.scala, src/main/scala/com/sksamuel/scapegoat/io/HtmlReportWriter.scala, src/test/scala/com/sksamuel/scapegoat/ConfigurationTest.scala, src/test/scala/com/sksamuel/scapegoat/FeedbackTest.scala, src/test/scala/com/sksamuel/scapegoat/LevelsTest.scala
refs #646
This one adds the `ignore` inspection level, allowing another way to suppress unneeded inspections along with `disable/enable` flags. 
The level name looks a bit alien to me, but `skip` is worse. Let me know if you have a better idea of the name.
=> SKIP level

README.md, src/main/scala/com/sksamuel/scapegoat/Configuration.scala, src/main/scala/com/sksamuel/scapegoat/io/GitlabCodeQualityReportWriter.scala, src/main/scala/com/sksamuel/scapegoat/io/IOUtils.scala, src/main/scala/com/sksamuel/scapegoat/plugin.scala, src/test/scala/com/sksamuel/scapegoat/TestConfiguration.scala, src/test/scala/com/sksamuel/scapegoat/io/GitlabCodeQualityReportWriterTest.scala
Add support to output GitLab Code Quality report format (Fixes #775).
Note: On multi module projects this will need support from the preferred build tool or trick (cat + jq?) to aggregate the jsons into one json.
The report requires project root relative paths to get correct links in the widgets. To this I used `CI_PROJECT_DIR` (https://docs.gitlab.com/ee/ci/variables/predefined_variables.html). If this turns out to not be flexible enough then maybe it could still become a config option for the report.
=> Support GitLab Code Quality report format

src/main/scala/com/sksamuel/scapegoat/io/HtmlReportWriter.scala, src/test/scala/com/sksamuel/scapegoat/io/HtmlReportWriterTest.scala
PointlessTypeBound inspection has angle brackets in the explanation. The HTML report tries to pretty format the code and parse it back to XML element which has dangling angle brackets causing failure.
Fixes https://github.com/scapegoat-scala/sbt-scapegoat/issues/175
=> fix: Angle brackets no longer cause malformed html reports

src/main/scala/com/sksamuel/scapegoat/inspections/unneccesary/UnnecessaryConversion.scala, src/main/scala/com/sksamuel/scapegoat/package.scala, src/test/scala/com/sksamuel/scapegoat/ScapegoatTest.scala, src/test/scala/com/sksamuel/scapegoat/inspections/unnecessary/UnnecessaryConversionTest.scala
Follow up on https://github.com/scapegoat-scala/scapegoat/pull/789#discussion_r1322663458 to allow minimum version checks rather than exact version matching.
This flow allows for each component to fail parsing which may quite defensive.
Triggered by a basic version update got a gotcha because we match on exact patterns: https://github.com/scapegoat-scala/scapegoat/pull/824
=> refactor: Decouple scala version checks from exact version list

.github/workflows/master-codecov.yml, .github/workflows/master-release.yml, .github/workflows/pr-checks.yml
Setup-scala is not maintained anymore and uses Node.js 16. Node.js 16 actions are deprecated. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
=> Migrate from setup-scala to setup-java action

build.sbt
So tooling can use it for eviction errors etc - https://www.scala-sbt.org/1.x/docs/Publishing.html
=> Add versionScheme early-semver to build.sbt

.github/workflows/pr-checks.yml, build.sbt, project/plugins.sbt, src/main/scala-3/com/sksamuel/scapegoat/Plugin.scala
=> feat: Support Scala 2.12.20 and 3.5.0

.github/workflows/pr-checks.yml, build.sbt
=> add scala 2.13.15

README.md, src/main/scala-2/com/sksamuel/scapegoat/Inspections.scala, src/main/scala-2/com/sksamuel/scapegoat/inspections/traits/AbstractTrait.scala, src/test/scala-2/com/sksamuel/scapegoat/inspections/traits/AbstractTraitTest.scala
Hello,
I implemented new inspection: check if trait is abstract (first from this list: https://github.com/scapegoat-scala/scapegoat/issues/302)
=> Add new inspection: abstract trait

README.md, src/main/scala-3/com/sksamuel/scapegoat/Inspections.scala, src/main/scala-3/com/sksamuel/scapegoat/Plugin.scala, src/main/scala-3/com/sksamuel/scapegoat/inspections/traits/AbstractTrait.scala, src/test/scala-3/com/sksamuel/scapegoat/inspections/traits/AbstractTraitTest.scala
Hello,
I returned with implementation of AbstractTrait check in scala 3
=> Add abstract trait inspections to scala3

README.md, src/main/scala-2/com/sksamuel/scapegoat/Inspections.scala, src/main/scala-2/com/sksamuel/scapegoat/inspections/AvoidRequire.scala, src/main/scala-3/com/sksamuel/scapegoat/Inspections.scala, src/main/scala-3/com/sksamuel/scapegoat/Plugin.scala, src/main/scala-3/com/sksamuel/scapegoat/inspections/AvoidRequire.scala, src/test/scala-2/com/sksamuel/scapegoat/inspections/AvoidRequireTest.scala, src/test/scala-3/com/sksamuel/scapegoat/inspections/AvoidRequireTest.scala
Hello,
fix for https://github.com/scapegoat-scala/scapegoat/issues/730
scala2/scala3
=> Add require check

src/test/scala-3/com/sksamuel/scapegoat/DottyRunner.scala, src/test/scala-3/com/sksamuel/scapegoat/ScapegoatPhaseTest.scala
Rewire ScapegoatPhaseTest to run Dotty instead of trying to mock the internal state of the compiler well enough to be able to test it directly. This will fix the errors caused by upgrading to 3.6.2 in #904
=> chore(tests): Avoid mocking internal compiler state to test phase actions

src/main/scala-2/com/sksamuel/scapegoat/inspections/VariableShadowing.scala, src/test/scala-2/com/sksamuel/scapegoat/inspections/VariableShadowingTest.scala
Closes #398.
The test only failed on Scala 2.12. Fixed by ignoring `_` variable names.
=> Fix false positive in VariableShadowing (#398)

.github/workflows/master-release.yml
**What**:
Switching from `ubuntu-latest` to `ubuntu-2204` for the release Github Action workflow.
**Why**:
In an attempt to address failures - #923.
=> ubuntu2204-for-release

.github/workflows/pr-checks.yml
**What**:
Similar to #924.
Switching from `ubuntu-latest` to `ubuntu-2204` for the CI.
**Why**:
- In an attempt to address failures - #923.
- TBH, I didn't investigate what would it take to run in the (new) `ubuntu-latest`. Maybe it's just some tiny thing...
=> Use ubuntu-22.04

.github/workflows/pr-checks.yml, build.sbt
Fixes #938.
Closes #926.
Closes #930.
According to previous examples project only keeps latest and latest LTS for Scala 3 - bumping both with this changeset.
=> Support for Scala 3.6.3 and 3.3.5

src/main/scala-3/com/sksamuel/scapegoat/Inspection.scala, src/main/scala-3/com/sksamuel/scapegoat/InspectionTraverser.scala, src/test/scala-3/com/sksamuel/scapegoat/InspectionTraverserTest.scala
> A test for our Scala 3 implementation for @SuppressWarnings.
Start of support for fine grained silencing through skipping any tree that is annotated with SuppressWarnings to aid in #944 .
Todo:
=> feat: Support Suppression of warnings on Scala 3
