- build.sbt
- src/main/scala/com/sksamuel/scapegoat/io/IOUtils.scala
- src/main/scala/com/sksamuel/scapegoat/io/ScalastyleReportWriter.scala
- src/main/scala/com/sksamuel/scapegoat/plugin.scala
- src/test/scala/com/sksamuel/scapegoat/PluginRunner.scala
Fix for [this](https://github.com/sksamuel/sbt-scapegoat/issues/16) issue in sbt-scapegoat plugin
> Scalastyle report format

- src/main/scala/com/sksamuel/scapegoat/Feedback.scala
- src/main/scala/com/sksamuel/scapegoat/Level.scala
- src/main/scala/com/sksamuel/scapegoat/plugin.scala
> Allow users to override the warning level for each inspection.

- src/main/scala/com/sksamuel/scapegoat/inspections/unneccesary/UnusedMethodParameter.scala
- src/test/scala/com/sksamuel/scapegoat/inspections/unnecessary/UnusedMethodParameterTest.scala
> #108 add unused constructor argument detection

- README.md
- src/main/scala/com/sksamuel/scapegoat/ScapegoatConfig.scala
@sksamuel Update the readme to bring it in sync with the latest inspections
> Update readme with latest inspections

- src/main/scala/com/sksamuel/scapegoat/inspections/naming/MethodNames.scala
- src/test/scala/com/sksamuel/scapegoat/inspections/names/MethodNamesTest.scala
> remove false positive: also allow setter method name (methodName_=)

- src/main/scala/com/sksamuel/scapegoat/inspections/collections/CollectionIndexOnNonIndexedSeq.scala
The change is based on this one (I don't know why that fixes the issue though):
https://github.com/tim-zh/wartremover/commit/691c2867751eace9f5b5c4d3a0d178131d4380b7
> #162 Don't use existential type.

- src/main/scala/com/sksamuel/scapegoat/inspections/collections/ReverseFunc.scala
* Don’t use existential type.
* Use extractor to avoid double map lookup.
> #166 Don’t use existential type

- src/main/scala/com/sksamuel/scapegoat/inspections/FinalModifierOnCaseClass.scala
- src/test/scala/com/sksamuel/scapegoat/inspections/FinalModifierOnCaseClassTest.scala
Fix for issue #170 
Skips the FinalModifierOnCaseClass inspection for abstract case classes.
> Fix issue #170

- src/main/scala/com/sksamuel/scapegoat/ScapegoatConfig.scala
- src/main/scala/com/sksamuel/scapegoat/inspections/collections/TraversableLast.scala
- src/test/scala/com/sksamuel/scapegoat/inspections/collections/TraversableLastTest.scala
Added a check for Traversable.last as this can cause the same problems as Traversable.head but doesn't get checked yet
> Added check for Traversable.last

- .gitignore
- src/main/scala/com/sksamuel/scapegoat/inspections/collections/UnsafeContains.scala
- src/test/scala/com/sksamuel/scapegoat/PluginRunner.scala
- src/test/scala/com/sksamuel/scapegoat/inspections/collections/UnsafeContainsTest.scala
> False positive unsafe contains

- src/main/scala/com/sksamuel/scapegoat/plugin.scala
Reports can be disabled with `none`
> Change help text

- src/main/scala/com/sksamuel/scapegoat/inspections/TypeShadowing.scala
- src/main/scala/com/sksamuel/scapegoat/inspections/collections/ComparisonToEmptyList.scala
- src/main/scala/com/sksamuel/scapegoat/inspections/collections/ComparisonToEmptySet.scala
- src/main/scala/com/sksamuel/scapegoat/inspections/collections/PreferSeqEmpty.scala
- src/main/scala/com/sksamuel/scapegoat/inspections/matching/PartialFunctionInsteadOfMatch.scala
- src/main/scala/com/sksamuel/scapegoat/inspections/matching/SuspiciousMatchOnClassObject.scala
- src/main/scala/com/sksamuel/scapegoat/inspections/math/NanComparison.scala
- src/main/scala/com/sksamuel/scapegoat/inspections/nulls/NullAssignment.scala
- src/main/scala/com/sksamuel/scapegoat/inspections/nulls/NullParameter.scala
- src/test/scala/com/sksamuel/scapegoat/PluginRunner.scala
procedure syntax is deprecated https://github.com/scala/scala/commit/1d4d901fcea0a162cd139836b246e85cc0130a6b
> fix procedure syntax

- src/main/scala/com/sksamuel/scapegoat/inspections/unneccesary/UnusedMethodParameter.scala
- src/test/scala/com/sksamuel/scapegoat/inspections/unnecessary/UnusedMethodParameterTest.scala
Added a special case to handle https://github.com/sksamuel/scapegoat/issues/105
> Ignore unused `args` parameter for main method

- README.md
refs https://github.com/sksamuel/scapegoat/issues/195
> Add Gradle section of README

- build.sbt
- src/main/scala/com/sksamuel/scapegoat/inspections/unneccesary/UnnecessaryToInt.scala
- src/test/scala/com/sksamuel/scapegoat/inspections/unnecessary/UnnecessaryToIntTest.scala
> Bugfix: null in UnnecessaryToInt

- README.md
- src/main/scala/com/sksamuel/scapegoat/ScapegoatConfig.scala
- src/main/scala/com/sksamuel/scapegoat/inspections/collections/PreferMapEmpty.scala
- src/test/scala/com/sksamuel/scapegoat/inspections/collections/PreferMapEmptyTest.scala
I suggest to add PreferMapEmpty rule that is a copy of PreferSetEmpty but with Set replaced with Map.
> added PreferMapEmpty rule

- src/main/scala/com/sksamuel/scapegoat/Inspection.scala
- src/main/scala/com/sksamuel/scapegoat/inspections/unneccesary/UnnecessaryConversion.scala
> Allow toSet conversion on mutable sets

- README.md
- src/main/scala/com/sksamuel/scapegoat/ScapegoatConfig.scala
- src/main/scala/com/sksamuel/scapegoat/inspections/controlflow/RepeatedIfElseBody.scala
- src/test/scala/com/sksamuel/scapegoat/inspections/controlflow/RepeatedIfElseBodyTest.scala
A new inspection to check if the main branch and the else branch of an `if` have the same code(Similar to repeated case bodies for a `match`), including:
- exact same code in both branches
- initial statement in both branches being the same
(EDIT: added more cases)
> New inspection: Repeated if else

- README.md
- src/main/scala/com/sksamuel/scapegoat/inspections/naming/MethodNames.scala
- src/test/scala/com/sksamuel/scapegoat/inspections/names/MethodNamesTest.scala
> False positive: Unary operators method names

- .travis.yml
Related to #278. Making Travis fetch tags
> Related to #278. Fetching tags

- src/main/scala/com/sksamuel/scapegoat/inspections/collections/PredefSeqIsMutable.scala
Minor clean-up after #301. See https://github.com/sksamuel/scapegoat/pull/301#discussion_r392684814
> [minor] removing redundant 213 check

- src/main/scala/com/sksamuel/scapegoat/Inspection.scala
- src/main/scala/com/sksamuel/scapegoat/inspections/LonelySealedTrait.scala
- src/main/scala/com/sksamuel/scapegoat/inspections/MaxParameters.scala
- src/main/scala/com/sksamuel/scapegoat/inspections/RedundantFinalModifierOnMethod.scala
- src/main/scala/com/sksamuel/scapegoat/inspections/TypeShadowing.scala
- src/main/scala/com/sksamuel/scapegoat/inspections/VariableShadowing.scala
- src/main/scala/com/sksamuel/scapegoat/inspections/collections/ExistsSimplifiableToContains.scala
- src/main/scala/com/sksamuel/scapegoat/inspections/collections/MapGetAndGetOrElse.scala
- src/main/scala/com/sksamuel/scapegoat/inspections/collections/PreferSeqEmpty.scala
- src/main/scala/com/sksamuel/scapegoat/inspections/collections/ReverseFunc.scala
- src/main/scala/com/sksamuel/scapegoat/inspections/collections/ReverseTailReverse.scala
- src/main/scala/com/sksamuel/scapegoat/inspections/collections/ReverseTakeReverse.scala
- src/main/scala/com/sksamuel/scapegoat/inspections/controlflow/RepeatedIfElseBody.scala
- src/main/scala/com/sksamuel/scapegoat/inspections/math/UseExpM1.scala
- src/main/scala/com/sksamuel/scapegoat/inspections/string/InvalidRegex.scala
- src/main/scala/com/sksamuel/scapegoat/inspections/style/ParameterlessMethodReturnsUnit.scala
- src/main/scala/com/sksamuel/scapegoat/inspections/unneccesary/VarCouldBeVal.scala
- src/main/scala/com/sksamuel/scapegoat/io/HtmlReportWriter.scala
- src/main/scala/com/sksamuel/scapegoat/io/IOUtils.scala
- src/main/scala/com/sksamuel/scapegoat/plugin.scala
- src/test/scala/com/sksamuel/scapegoat/inspections/collections/UnsafeTraversableMethodsTest.scala
Cleaning-up code. Partly based on #305. Partly using Intellij Inspections
> Warnings clean up

- .github/workflows/master-codecov.yml
- .github/workflows/pr-checks.yml
- build.sbt
> Add a codecov workflow for master.

- project/plugins.sbt
- src/main/scala/com/sksamuel/scapegoat/inspections/VariableShadowing.scala
- src/test/scala/com/sksamuel/scapegoat/inspections/VariableShadowingTest.scala
> shadowing two fors

- README.md
- src/main/scala/com/sksamuel/scapegoat/io/HtmlReportWriter.scala
- src/main/scala/com/sksamuel/scapegoat/io/IOUtils.scala
- src/main/scala/com/sksamuel/scapegoat/io/MarkdownReportWriter.scala
- src/main/scala/com/sksamuel/scapegoat/io/ReportWriter.scala
- src/main/scala/com/sksamuel/scapegoat/io/ScalastyleReportWriter.scala
- src/main/scala/com/sksamuel/scapegoat/io/XmlReportWriter.scala
- src/main/scala/com/sksamuel/scapegoat/plugin.scala
- src/test/scala/com/sksamuel/scapegoat/FeedbackTest.scala
- src/test/scala/com/sksamuel/scapegoat/PluginRunner.scala
- src/test/scala/com/sksamuel/scapegoat/inspections/FinalModifierOnCaseClassTest.scala
- src/test/scala/com/sksamuel/scapegoat/inspections/collections/MapGetAndGetOrElseTest.scala
* Clean up and unification of reporters code
* Introduces markdown report type, fixes  #334
Example of markdown report:
> Improved reports, markdown report

- src/main/scala/com/sksamuel/scapegoat/inspections/unneccesary/UnusedMethodParameter.scala
- src/test/scala-2.13/com/sksamuel/scapegoat/inspections/unnecessary/UnusedMethodParameterTest213.scala
> UnusedMethodParameter honors @unused annotation now

- .github/workflows/master-codecov.yml
- .github/workflows/master-release.yml
- .github/workflows/pr-checks.yml
- build.sbt
- src/main/scala/com/sksamuel/scapegoat/inspections/collections/ComparisonToEmptyList.scala
> Add Scala 2.13.4 support

- src/test/scala/com/sksamuel/scapegoat/inspections/math/UseExpM1Test.scala
- src/test/scala/com/sksamuel/scapegoat/inspections/math/UseLog10Test.scala
Minor refactoring. The tests for inspections should extends `InspectionTest`
> Using InspectionTest

- src/main/scala/com/sksamuel/scapegoat/inspections/inference/PointlessTypeBounds.scala
- src/test/scala/com/sksamuel/scapegoat/inspections/inferrence/PointlessTypeBoundsTest.scala
fixes https://github.com/scapegoat-scala/scapegoat/issues/415
> Reduce false positives for `PointlessTypeBounds`

- .github/workflows/pr-checks.yml
- build.sbt
- project/plugins.sbt
After this you can release a new version
> Support Scala 2.13.11

- .github/workflows/pr-checks.yml
- build.sbt
- project/plugins.sbt
Fixes #839.
Closes #838.
Co-authored by @gaeljw.
> Support Scala 2.13.14

- .github/workflows/pr-checks.yml
- src/main/scala-3/com/sksamuel/scapegoat/inspections/AvoidRequire.scala
Fixes #911.
Also formats one file to succeed the GitHub Actions.
> #911: Check formatting in GitHub Actions

- .github/workflows/pr-checks.yml
- build.sbt
- src/test/scala-3/com/sksamuel/scapegoat/inspections/option/OptionGetTest.scala
> Support Scala 3.6.2

- .github/workflows/pr-checks.yml
- build.sbt
> feat: Support Scala 3.6.4

- .github/workflows/pr-checks.yml
- build.sbt
- src/main/scala-3/com/sksamuel/scapegoat/InspectionTraverser.scala
- src/main/scala-3/com/sksamuel/scapegoat/Plugin.scala
- src/test/scala-3/com/sksamuel/scapegoat/DottyRunner.scala
Adds latest LTS and non-LTS Scala 3 GA releases:
* https://github.com/scala/scala3/releases/tag/3.3.6
* https://github.com/scala/scala3/releases/tag/3.7.0
> feat: Support Scala 3.3.6 and 3.7.0
